### ISSUE TITLE
tigase sends starttls stream feature over Websocket

### ISSUE THREAD

**Issue by sonnyp** [tigase/tigase-server#10]
**Describe the bug**

After connecting with WebSocket and opening the "stream", Tigase sends the `<starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>` stream feature which is not compatible with WebSocket.

**Expected behavior**

Tigase does not send  `<starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>`  stream feature for WebSocket connections.

**Comment by sonnyp** [comment]
The same issue affected prosody a while ago https://issues.prosody.im/837

I did not reproduce myself, the issue was reported by an `xmpp.js` user see https://github.com/xmppjs/xmpp.js/issues/807

**Comment by hantu85** [comment]
I've just fixed the issue and added a test case for our tests which are executed daily. Tomorrow's SNAPSHOT build of Tigase XMPP Server 8.1.0 will contain a fix for this issue.
