### ISSUE TITLE
No supported and enabled SASL Mechanism provided by server

### ISSUE THREAD

**Issue by kotlin711** [tigase/tigase-server#100]
**I have a problem with…**
A clear and concise description of what the problem is.

**Details (please complete the following information):**
 - Tigase version: 8.1.0
 - OpenJDK11
![image](https://user-images.githubusercontent.com/86459514/128200604-843faab8-6191-4e33-94e7-11729bf5e0fc.png)

**Comment by kotlin711** [comment]
![image](https://user-images.githubusercontent.com/86459514/128208144-08a63d8b-4bc9-4abd-b971-22db0a479521.png)
I solved

**Comment by kotlin711** [comment]
![image](https://user-images.githubusercontent.com/86459514/128211121-a871a373-b4a4-4b0c-bb55-815bcab7e48f.png)
![image](https://user-images.githubusercontent.com/86459514/128211249-207f1be4-2648-4d47-a62c-c3e38c8c8a5e.png)

**Comment by woj-tek** [comment]
Can you state the actual problem?

Can you clarify which version do you use? In the first message you put "8.1.0" but then you shared screenshot from configuration which is in 7.x format.
