### ISSUE TITLE
A bug occurred during startup,titase 8.1.2,MongoDB 3.2.22,jdk 11

### ISSUE THREAD

**Issue by miraclewon** [tigase/tigase-server#104]
config.tdsl:
admins = [ 'admin@127.0.0.1' ]
'config-type' = 'default'
debug = [ 'server' ]
'default-virtual-host' = '127.0.0.1'
dataSource {
    default () {
        uri = 'mongodb://tigase:tigase@localhost:27017/tigasedb'
    }
}
userRepository {
    default () {
        cls = 'mongodb'
    }
}
authRepository {
    default () {}
}
http (class: tigase.http.HttpMessageReceiver) {}
'sess-man' () {}

=====================

Could not initialize bean default (class: class tigase.db.beans.DataSourceBean$DataSourceMDConfigBean), skipping injection of this bean
RootCause:
   -> tigase.kernel.KernelException: Cannot inject configuration to bean default
      [tigase.kernel.beans.config.AbstractBeanConfigurator.configure(AbstractBeanConfigurator.java:400)]
      -> java.lang.RuntimeException: Could not initialize tigase.db.DataSource for name 'default'
         [tigase.db.beans.MDPoolConfigBean.beanConfigurationChanged(MDPoolConfigBean.java:109)]
         -> java.lang.ClassNotFoundException: tigase.db.util.SchemaManager.DataSourceInfo
            [java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)]

=====================

Enter breakpoint，the actual exception is "java.lang.ClassNotFoundException: tigase.db.util.SchemaManager.DataSourceInfo"

**Comment by woj-tek** [comment]
For future reference: what was the issue and how did you solved it? (it looks like missing dependency library?)

**Comment by miraclewon** [comment]
> For future reference: what was the issue and how did you solved it? (it looks like missing dependency library?)

I solved it by  importing other components like tigase-mongodb.but  I have other difficulties and need your help,https://github.com/tigase/tigase-server/issues/105
