### ISSUE TITLE
tigase8.1.2 api cannot be used

### ISSUE THREAD

**Issue by fullky** [tigase/tigase-server#118]
**I have a problem with…**
When I use java to call the API in rest, I report the error "to access URI = '/ rest / stream /' a valid API key is required". I added an apikey in the admin page, but it is useless. There is no init.properties file in the etc directory of version 8.1.2. Do I need to create it myself

**Details **
 - Tigase version:  8.1.2
 - JVM flavour and version AdoptOpenJDK11
 - Operating system/distribution/version centos 7

**Comment by fullky** [comment]
This is my code
![image](https://user-images.githubusercontent.com/91643533/136502682-ee72bf7e-60f4-41ac-9aeb-cff5eba24204.png)
![image](https://user-images.githubusercontent.com/91643533/136502745-a134b0c0-76a3-4697-9f8c-6f43a9ba23f1.png)

**Comment by fullky** [comment]
![image](https://user-images.githubusercontent.com/91643533/136508297-be04542f-0cd6-440a-a821-73de871f6529.png)
I added these to the configuration file, but it still doesn't work...

**Comment by hantu85** [comment]
As stated at https://docs.tigase.net/tigase-http-api/stable-snapshot/Tigase_HTTP-API_Guide/html/ you need to pass `api-key` as a parameter and not `api_key` as you did. Please see mentioned documentation for more hints and suggestions.
