### ISSUE TITLE
Tigase XMPP Server Fails to Function as Intended

### ISSUE THREAD

**Issue by one-and-only** [tigase/tigase-server#127]
**Describe the bug**
Tigase XMPP Server fails to accept client connections on the default XMPP ports and an HTTP 400 error occurs when trying to connect to the default WebSocket port of 5290.

**To Reproduce**
1. Download the `dist-max` version of Tigase XMPP Server from the official download link at [tigase.net](https://tigase.net/xmpp-server/)
2. Follow the instructions for installing via the Web Installer (Make sure to disable message archive as that seemed to be broken for me and failed to initialize)
    i. To make it easier, just choose the Derby database
3. Save the configuration from the web installer and restart the server to apply the changes
4. Try and login through the XMPP port using the admin account and watch it not even connect to the server

**Impact**
Unable to use the default XMPP ports 5222 or 5223 as described in the web installer instructions (even the admin account won't sign in). The XMPP client is unable to connect to the server. Trying a WebSocket connection with *Postman* yielded an HTTP 400 error on the default XMPP port 5290.

**Expected behavior**
Be able to at least connect to the default websocket port, let alone send an XMPP stanza (also be able to use the default XMPP ports `5222` and `5223`

**Screenshots**
This is what I get when I try and connect to the websocket port using *Postman*
![Postman Tigase XMPP WebSocket Error](https://i.imgur.com/tS0lAZN.png)

**Details (please complete the following information):**
 - Tigase version: `8.0.0-b10083/6923973a`
 - JVM flavour and version: `OpenJDK 11`
 - Operating system/distribution/version: `Debian 10 aarch64` (on raspberry pi)

**Additional context**
I have tried server versions 7.1.1, 8.0.0, and 8.1.2 to mo avail.
I don't think anything else is needed, but more information is available upon request

**Comment by woj-tek** [comment]
Could you try latest stable release from https://github.com/tigase/tigase-server/releases, ie. 8.1.2: https://github.com/tigase/tigase-server/releases/download/tigase-server-8.1.2/tigase-server-8.1.2-b10915-dist-max.zip

**Comment by hantu85** [comment]
WebSocket port is only for XMPP over WebSocket connections, see https://datatracker.ietf.org/doc/html/rfc7395

According to this specification, you are missing `Sec-WebSocket-Protocol: xmpp` header in your request and Tigase may reject those requests as you have not specified any protocol known to Tigase XMPP Server.

**Comment by one-and-only** [comment]
> Could you try latest stable release from https://github.com/tigase/tigase-server/releases, ie. 8.1.2: https://github.com/tigase/tigase-server/releases/download/tigase-server-8.1.2/tigase-server-8.1.2-b10915-dist-max.zip

I have tried that version along with a few others, to no avail. I updated my issue to include this

**Comment by one-and-only** [comment]
> WebSocket port is only for XMPP over WebSocket connections, see https://datatracker.ietf.org/doc/html/rfc7395
> 
> According to this specification, you are missing `Sec-WebSocket-Protocol: xmpp` header in your request and Tigase may reject those requests as you have not specified any protocol known to Tigase XMPP Server.

This solved my WebSocket issue, thank you!

**Comment by one-and-only** [comment]
I don't seem to be getting a response from the server when sending various XMPP stanzas via the websocket. Is there something I could use to test with? I have tried `<open />`, `<message ...>.....</message>`, and message history request. `<open />` was the only one that I expected to get a response for, as `<message>` doesn't return anything and I have message archiving disabled.
