### ISSUE TITLE
Tigase XMPP REST API Documentation is Lacking

### ISSUE THREAD

**Issue by one-and-only** [tigase/tigase-server#128]
**I have a problem with…**
Finding the right parameters for REST API endpoints. I am trying to "fix" a user's roster through the REST API, but I am having trouble finding the necessary parameters needed for such an operation. I have found that I need to execute an AdHoc command for the node `roster-fixer`, but there is no documentation that I could find which lists the required XML/JSON data that needs to be passed into the body to make it work.

**Details (please complete the following information):**
 - Tigase version: `8.0.0-b10083/6923973a`
 - JVM flavour and version `OpenJDK 11`
 - Operating system/distribution/version: `Debian 10 aarch64`

**Comment by woj-tek** [comment]
Have you seen [Retrieving list of available adhoc commands](https://docs.tigase.net/tigase-server/master-snapshot/Development_Guide/html/#_retrieving_list_of_available_adhoc_commands) and [Retrieving command form](https://docs.tigase.net/tigase-server/master-snapshot/Development_Guide/html/#RetrievingCommandForm). This should give you enough information what is the structure and fields.

**Comment by one-and-only** [comment]
Thank you for the information. I got as far as the first link, but could never come across information in the second link. This has resolved my issue. Thanks again.
