### ISSUE TITLE
extension muc message not storage database in message archive component

### ISSUE THREAD

**Issue by ChenAdminChen** [tigase/tigase-server#13]
**Describe**
1. tigase 8.0.0-b10083  version
2. mysql 5.7.21
3. message archive component(message-archive=4:2318, version: 2.0.0-b241/06879836)

**configuration in config.tdsl**

```
'config-type' = 'default'

'default-virtual-host' = 'im.com'

debug = ['db' , 'server' , 'xmpp.XMPPIOService' ]

dataSource {

    default () {
        uri = 'jdbc:mysql://localhost:3306/tigase8?user=test&password=test&useSSL=false&autoCreateUser=true'
    }
}

muc () {
    'message-filter-enabled' = false
}

message-archive {
        'default-store-method' = 'message'
        'store-muc-messages' = 'true' 
}

sess-man {
    message-archive {
        'default-store-method' = 'message'
        'store-muc-messages' = 'true' 
    }

    message-archive-xep-0136 () {
    }

    urn:xmpp:mam:1 () {
    }
}
```

**describe**

question 1 : what can I do,  server can auto storage message？ I want storage ` <message>......</message> `

```
-- send to server
<iq type='get' id='prefq'>
  <pref xmlns='urn:xmpp:archive'/>
</iq>

--  recevie
<iq to="chen@im.com/Psi+" id="prefq" type="result">
<pref xmlns="urn:xmpp:archive">
<auto save="false"/>
<default otr="forbid" save="message" muc-save="false"/>
<method use="prefer" type="auto"/>
<method use="prefer" type="local"/>
<method use="prefer" type="manual"/>
</pref>
</iq>
```
message not auto archive,  if client send `<auto save="true"/>` iq message to server,  server can  storage this client message

```
-- send to server
<iq type='set' id='prefq'>
  <pref xmlns='urn:xmpp:archive'>
<auto save="true"/>
</pref>
</iq>

<iq type='get' id='prefq'>
  <pref xmlns='urn:xmpp:archive'/>
</iq>

--recevie
<iq to="chen@im.com/Psi+" id="prefq" type="result">
<pref xmlns="urn:xmpp:archive">
<auto save="true"/>
<default otr="forbid" save="message" muc-save="false"/>
<method use="prefer" type="auto"/>
<method use="prefer" type="local"/>
<method use="prefer" type="manual"/>
</pref>
</iq>

```

question 2 : what can I do,  muc extension message  can be  message archive, storage  <message>......</message>

+ one to one chart
1.
```
<message to="kevin@im.com/Psi+" id="ab4ba" type="chat">
<body>fsdf</body>
<request xmlns="urn:xmpp:receipts"/>
</message>

```

2.
```
<message to="kevin@im.com/Psi+" id="ab4ba" type="chat">
<body>test</body>
<test>extension message</test>
<request xmlns="urn:xmpp:receipts"/>
</message>
```

+ groupchart

3. 
```
<message to="chen@im.com/Psi+" id="ab4fa" type="groupchat" from="mam@muc.im.com/chen">
<body>test</body>
</message>
```

4.
```
<message to="chen@im.com/Psi+" id="ab4fa" type="groupchat" from="mam@muc.im.com/chen">
<body>test</body>
<test xmlns="xxx:test"> muc extension message</test>
</message>
```

1, 2, 3 can be storage in database, but 4 can not be storgae in database?????

please help me !!!!!!!

**Comment by woj-tek** [comment]
> question 1 : what can I do, server can auto storage message？ I want storage <message>......</message>

You should use [`required-store-method`](https://docs.tigase.net/tigase-message-archiving/master-snapshot/Tigase_Message_Archiving_Guide/html/#_setting_required_value_of_archiving_level_for_messages_on_a_server) - it enforces minimal level or message archive (so user won't be able to disable it)

> question 2 : what can I do, muc extension message can be message archive, storage ......

Was the stanza message stored in the database ("test") or there is no trace at all of the message with that ID?

**Comment by ChenAdminChen** [comment]
1. yes, you're right, `required-store-method = true`is the key,  tigase  server can auto message archive
2. muc extension message can be stored,not problem
