### ISSUE TITLE
How to cancel disable user?

### ISSUE THREAD

**Issue by zeronlee** [tigase/tigase-server#14]
I use tigase8.0 server with mysql, client with stropheJs. I find disabled users everyday.
the table `tig_users.account_status`=0. I update this field equal 1, when I refresh page, the tig_users table appear account_status=0 again, I don't know why?

I search with keyworld in source code, the `tigase/db/derby/StoredProcedures.java` tigDisableAccount function execute relation work, but I don't know where to call it?

please give me help, online Waiting!

**Comment by woj-tek** [comment]
Please provide more details and your configuration file as this depends on various conditions and on your configuration. If you use captcha or email verification then your users have to confirm e-mail address before the account is activated.

**Comment by zeronlee** [comment]
this is my tig_users table detail:

| uid  | user_id              | user_pw | online_status | failed_logins | account_status |
| ---- | -------------------- | ------- | ------------- | ------------- | -------------- |
| 6297 | im6152@192.168.2.133 |       |   0             | 0             | 0              |

when the field `account_status` equal 1, the user can not login.

I use sql `UPDATE tig_users SET account_status = 1 WHERE account_status = 0;`, after a while, I use `SELECT *  FROM tig_users  WHERE account_status = 0;`, some users appear again ，and these users are random.

Here is all content of  my `config.tdsl`:
```
admins = [ 'admin' ]
'config-type' = 'default'
debug = [ 'server' ]
'default-virtual-host' = '127.0.0.1'
dataSource () {
    default () {
        uri = 'jdbc:mysql://localhost/tigasedb?user=root&password=root&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true'
    }
}
http () {
    setup () {
        'admin-password' = 'tigase'
        'admin-user' = 'admin'
    }
}
'message-archive' {
    'archive-repo-uri' = 'jdbc:mysql://localhost/tigasedb?user=root&password=root&useUnicode=true&characterEncoding=UTF-8'
    'msg-archive-paths' = [ '/message/body', '/message/subject' ]
    'tags-support' = true
}
muc {
    'muc-lock-new-room' = false
    default_room_config {
        maxhistoryfetch = 0
        roomconfig_membersonly = false
        roomconfig_persistentroom = true
    }
}
pubsub () {
    trusted = [ 'http@{clusterNode}' ]
}
'sess-man' {
    'message-archive' {
        'default-store-method' = 'message'
        'required-store-method' = 'body'
    }
    'urn:xmpp:mam:1' () {}
    'urn:xmpp:ping' () {}
        'brute-force-locker' () {
                detailedStatistics = false
        }
}
```

**Comment by woj-tek** [comment]
1. Do you use tigase-spam (module that helps fighting spam messages)? It could deactivate account. you Can check `etc/config-dump.properties` and check whether spam module is enabled or not in your case (it's enabled by default and I'm not sure whether you haven't disabled it). You can check [Tigase SPAM Filter](https://docs.tigase.net/tigase-spam/master-snapshot/Tigase_SPAM_Guide/html/) for more details. To disable it altogether you can use:
```
'sess-man () {
    'spam-filter' (active: false) {}
}
```

2. Do you make any REST API to Tigase?

**Comment by zeronlee** [comment]
1. Today, I checked `tigase-console.log` file and found:
```
sess-man/BruteForceLocker/From IP: 192.168.2.137[I] = 3004
sess-man/BruteForceLocker/For JID: im7970@192.168.2.133[I] = 4
```
These jids happen to be users in the data table tig_users.account_status = 0， so I search keyworld in `https://docs.tigase.net/tigase-server/8.0.0/Administration_Guide/html/#bruteForcePrevention`, found configuration item ,Here is my configuration:
```
'sess-man' {
    'message-archive' {
        'default-store-method' = 'message'
        'required-store-method' = 'body'
    }
    'urn:xmpp:mam:1' () {}
    'urn:xmpp:ping' () {}
    'brute-force-locker'{
	'brute-force-lock-enabled' = false
    }
    'spam-filter' (active: false) {}
}
```
but, did not help, How do I configure it correctly?

2. I am useless any REST API to Tigase.
Thanks!

**Comment by woj-tek** [comment]
Please try this way:
```
'sess-man' {
    'message-archive' {
        'default-store-method' = 'message'
        'required-store-method' = 'body'
    }
    'urn:xmpp:mam:1' () {}
    'urn:xmpp:ping' () {}
    'brute-force-locker' (active: false){}
    'spam-filter' (active: false) {}
}
```

You can also disable it on per-domain basis in VHost configuration (Using admin WebUI)

**Comment by zeronlee** [comment]
Thanks very much!
