### ISSUE TITLE
Security bugfix in tigase-xmltools v8.1.x branch

### ISSUE THREAD

**Issue by davidemarrone** [tigase/tigase-server#145]
Hi,
I want to know if you are going  to release a security fix also for the 8.1.x branch

I saw that for example the v8.1.1-b10861 version contains:
tigase-xmltools: 4.1.0-b287

instead the latest 8.2.1 contains:
tigase-xmltools: 4.1.1-b293

if you are not going to release a fix on the 8.1.x branch, could I just overwrite the tigase-xmltools.jar in the 8.1.x release with the latest 4.1.1-b293 to fix the problem?

regards

**Comment by woj-tek** [comment]
Hi,
we are not going to make release for 8.1.x branch as we consider it "8 release". As you dully noticed, we also released `tigase-xmltools-4.1.1` which indeed can be used to apply the fix to 8.1.x release by simply replacing `tigase-xmltools.jar` binary.

We of course encourage everyone to upgrade to the latest 8.2.x release.
