### ISSUE TITLE
SQL Server driver throws an exception on latest 8.3.0 builds

### ISSUE THREAD

**Issue by maranda** [tigase/tigase-server#159]
**Describe the bug**
The SQL Server DB Driver is broken on JDK 17 and throws this exception:
`Problem validating database connection: java.lang.NoClassDefFoundError: org/ietf/jgss/GSSException`

**To Reproduce**
1. Do web install
2. Select SQL Server as DB Backend
3. Try to authenticate with SQL Server

**Impact**
Can't use SQL Server as DB Backend

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Tigase version: 8.3.0
 - JVM flavour and version [e.g. OpenJDK17]
 - Windows Server 2022 on WSL2 Docker (Docker Desktop)

**Comment by woj-tek** [comment]
Could you share complete logs from the console (including complete stacktrace)?

Which 8.3.0 release did you you exactly (flavour, build number, download link)?

**Comment by maranda** [comment]
I'd have to replicate the environment again for the traces, anyhow I tested against SQL Server 2019 and replicated the issue over all the 8.3 nightlies I found on dockerhub.
While on latest builds (8.2.1) it works although the schema update always fails at admin adding/post actions. The only difference appears to be Jdk11 vs. Jdk17.
