### ISSUE TITLE
How can I implement the use of MDC in tigase logs? Any sugestions?

### ISSUE THREAD

**Issue by FelipeIregui** [tigase/tigase-server#174]
**I have a problem with…**
Difficulties using MDC in tigase logs. trying to integrate a correlation id in logs. 

**Details (please complete the following information):**
 - Tigase version: 8.1.0
 - AdoptOpenJDK11
 - Linux Ubuntu 20.04

**Comment by woj-tek** [comment]
I assume that MDC stands here for Mapped Diagnostic Context?

Currently, we use JUL logger and from what I read it doesn't support MDC so adding support for it would require complete overhaul of logging in Tigase. What's more, considering that Tigase is multi-component and multi-threaded, passing correctly id between would be problematic.

Though, we do include packet in most of the log entries so tracking packet processing (using it's ID) should be fine.

**Comment by FelipeIregui** [comment]
Yeah :). Perfect thank you, will try the tracking on each packet logs.
