### ISSUE TITLE
How to contribute to the project?

### ISSUE THREAD

**Issue by karapirinc** [tigase/tigase-server#178]
Hi!
I would like to contribute to the project but I don't have the correct access rights.
Also, I couldn't find the guideline, if there is any. 

Best,

**Comment by woj-tek** [comment]
We welcome contributions. If you would like to do so, you should [fork the repository](https://github.com/tigase/tigase-server/fork), make the changes and then create Pull Request.

**Comment by karapirinc** [comment]
Thanks.
