### ISSUE TITLE
Activation of Offline Presence Plugin

### ISSUE THREAD

**Issue by FelipeIregui** [tigase/tigase-server#180]
**I have a problem with…**
Hi, Im having issues regarding the activation of the offline presence plugin, since when it is activated the consumption of server and db resources grows to the roof and may start failing other proceses. 
I think that this growth in consumption will stabilized in some point after few hours if we increase cache max entries. Is this correct?
Do you have any other suggestions to minimized this growth?
Thank You very much. 

**Details (please complete the following information):**
 - Tigase version: 8.1.0
 - AdoptOpenJDK11
 - Linux Ubuntu 20.04

**Comment by woj-tek** [comment]
Could you be more specific regarding "consumption of server and db resources grows to the roof and may start failing other proceses."

Do you mean CPU? Memory? Storage of the DB?

The plugin uses cache but it also relies on database to persist presence data. Number of DB requests could be significant in case of frequent reconnects (mobile OS without stream management for example).

**Comment by woj-tek** [comment]
OK, it seems that mostly RDS metrics are affected thus it would indicate higher number of queries which in turn would suggest that indeed *increasing cache size (and thus reducing number of queries) should help*.

If you are using RDS, do you have performance insights enabled and could share information from it? Which queries are the biggest offenders? I would assume `TigUpdatePairs` and `select pval from tig_pairs…`

**Comment by FelipeIregui** [comment]
Thank You!
Would try and see what can be done. 
Actually yes, all regarding tig_pairs are very paintful buut we are also encountering issues with normal selects and counts to tig_users.
