### ISSUE TITLE
documentation of old versions

### ISSUE THREAD

**Issue by davidemarrone** [tigase/tigase-server#191]
Hi,
were I can find the documentation of old versions of tigase like 7.x or 8.1.x?

Here is not more available:
https://docs.tigase.net/

Does tigase 8.1.1 support mysql 8?

regards

**Comment by woj-tek** [comment]
There is a section [Legacy documentation website](https://docs.tigase.net/en/latest/#legacy-documentation-website) which links to https://docs-legacy.tigase.net/

Yes, Tigase 8.1.x support MySQL 8, though we would recommend using latest stable Tigase version.

**Comment by davidemarrone** [comment]
thank you very much! I will make also a local copy for the future

**Comment by woj-tek** [comment]
The documentation is (well, was) generated from AsciiDoc files and those are in the repository: https://github.com/tigase/tigase-server/tree/tigase-server-8.1.1/src/main/asciidoc/admin
