### ISSUE TITLE
official Docker container

### ISSUE THREAD

**Issue by alexanderadam** [tigase/tigase-server#2]
It would be wonderful if there would be an [_official_ Docker container on Docker hub](https://hub.docker.com/search?q=tigase&type=image) because at the moment there seem to be a bunch of inofficial and outdated ones.

Thank you for your work! :pray:

**Comment by arturhefczyc** [comment]
Yes, indeed. We are working on this. We have first working version and expect to publish it in next weeks.

**Comment by alexanderadam** [comment]
Awesome! :tada:

**Comment by Neustradamus** [comment]
@arturhefczyc: Maybe good to close this ticket?
- https://github.com/tigase/tigase-docker-support
