### ISSUE TITLE
How to delete a message from group chat

### ISSUE THREAD

**Issue by trunghm** [tigase/tigase-server#21]
Hello there,

Can you please advise whether tigase supports deleting a message from group chat from a participant (not from admin/moderator)?

I see there's experimental standard for message deletion at http://legastero.github.io/customxeps/extensions/message-delete.html, is this supported by tigase?

If there's no supported yet, would you please advise which standard I should follow to delete a message from group chat and the archived message histories?

Thanks,
Trung

**Comment by hantu85** [comment]
Our group chat component does not have any mechanism of message deletion/removal/retraction. In the case of group chats, you need to consider not only the removal of the message from the message archive of the group chat but also removal from a local message history that is stored by the XMPP clients.

A linked specification is not a standard, not even an experimental standard as it is not posted at https://xmpp.org/extensions/.

We are considering adding this feature (message retraction) in the future and most likely we will follow https://xmpp.org/extensions/xep-0424.html which is an experimental XEP (experimental specification which may become an extension of XMPP protocol).

**Comment by trunghm** [comment]
Thank you for your reply. Yes, we wanted to delete the message in both archived messages in server and in XMPP clients. For clients, we can do some workaround to delete the message for now, but we don't know how to delete the message from archived messages. While we're waiting for the Xep-0424 to be implemented, would you please advise if there's a way to delete the message from archived messages (e.g. using a rest API, or accessing to database to look for the message and delete it)?

**Comment by trunghm** [comment]
Hi again,

Also, would you please check and confirm if server already supports https://xmpp.org/extensions/xep-0425.html?

Many thanks,
Trung

**Comment by hantu85** [comment]
No, the server does not have support for this XEP. This XEP is still experimental and the last version was published on the 28th of January 2020, so it is not even a month old.

**Comment by trunghm** [comment]
Thank you for your kind support!
