### ISSUE TITLE
Readme Quickstart Link broken

### ISSUE THREAD

**Issue by albsch** [tigase/tigase-server#217]
It seems that the link in the Readme is broken:

https://docs.tigase.net/tigase-server/snapshot/Administration_Guide/html/#QuickStart

It redirects to:

https://docs-legacy.tigase.net/tigase-server/snapshot/Administration_Guide/html/#QuickStart

and throws, at least for me,  a `404` error.

The link that works for me is:

https://docs.tigase.net/en/latest/Tigase_Administration/Quick_Start_Guide/Intro.html

**Comment by hantu85** [comment]
Thank you for reporting this issue. I've fixed link.
