### ISSUE TITLE
8.3.1 version 

### ISSUE THREAD

**Issue by Tojay12** [tigase/tigase-server#220]
does not exist class  MongoSchemaLoader.class
![1711521075514](https://github.com/tigase/tigase-server/assets/45176148/b3eb5544-d281-43f7-99b0-460d7a313aa1)

**Comment by hantu85** [comment]
Class `MongoSchemaLoader` is not part of the Tigase XMPP Server source code but it is a part of [Tigase MongoDB](https://tigase.dev/tigase/_server/tigase-mongodb/~files) project that provides support for storing data in MongoDB. Most likely you need to include it in your project.
