### ISSUE TITLE
Documentation: Bad links

### ISSUE THREAD

**Issue by Neustradamus** [tigase/tigase-server#46]
Bad links:

https://docs.tigase.net/tigase-server/stable-snapshot/Administration_Guide/html/
-> 8.0.x
It must be 8.1.x

https://docs.tigase.net/tigase-server/old-stable-snapshot/Administration_Guide/html/
-> does not work
It must be 8.0.x

I have not tested other projects...

**Comment by woj-tek** [comment]
Thank you for reporting it, we will look into it.


(ref: https://projects.tigase.net/issue/prv-486)
