### ISSUE TITLE
xmpp-sasl setting doesn't work

### ISSUE THREAD

**Issue by supanwoc** [tigase/tigase-server#47]
```
 'urn:ietf:params:xml:ns:xmpp-sasl' () {
     'callbackhandler-PLAIN'='com.eliao.tigase.RedisCallbackHandler'
}
```

**Comment by hantu85** [comment]
This processor works as expected. Please check documentation for usage of custom SASL callback handlers as your configuration is invalid, see https://docs.tigase.net/tigase-server/8.1.0/Development_Guide/html/#saslcmac

**Comment by supanwoc** [comment]
Here is my configuration，nothing else。What's wrong
'sess-man' (class: com.demo.tigase.DemoSessionManager) {
    'urn:ietf:params:xml:ns:xmpp-sasl' () {
        'callbackhandler' = 'com.demo.tigase.RedisCallbackHandler'
     }
}

**Comment by supanwoc** [comment]
I use version 8.0

**Comment by woj-tek** [comment]
Could you explain what does it mean "doesn't work"? Does it generates errors/exceptions? Or the expected result differ?

Please also explain what are you trying to achieve.

Btw. We recently released 8.1.0 (https://github.com/tigase/tigase-server/releases/tag/tigase-server-8.1.0) and it's recommendable to use this version.

**Comment by supanwoc** [comment]
thank you！It's ok now

**Comment by supanwoc** [comment]
There are the following content in the config.tdsl file
'sess-man' (class: com.demo.tigase.DemoSessionManager) {
    'urn:ietf:params:xml:ns:xmpp-sasl' () {
        'callbackhandler' = 'com.demo.tigase.RedisCallbackHandler'
     }
}
but in ‘config-dump.properties’ file ，There is no information about ‘com.demo.tigase.RedisCallbackHandler’，This is OK in 7.1.3。
 'urn:ietf:params:xml:ns:xmpp-sasl' (class: tigase.xmpp.impl.SaslAuth) {
        queueSize = null
        threadsNo = 32
}

also RedisCallbackHandler  is not running. 

That's what I said "doesn't work"

It was solved in other ways
