### ISSUE TITLE
muc.tigase.org certificate expired

### ISSUE THREAD

**Issue by mwlczk** [tigase/tigase-server#48]
openssl s_client  -connect muc.tigase.org:5269 -starttls xmpp
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = tigase.org
**verify error:num=10:certificate has expired
notAfter=Aug  1 04:11:20 2020 GMT
verify return:1
depth=0 CN = tigase.org
notAfter=Aug  1 04:11:20 2020 GMT**
verify return:1

Certificate chain
 0 s:CN = tigase.org
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3

Server certificate
-----BEGIN CERTIFICATE-----
MIIFkzCCBHugAwIBAgISBD5FOc+0rV6+bi/DLtYJKTYDMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDA1MDMwNDExMjBaFw0y
MDA4MDEwNDExMjBaMBUxEzARBgNVBAMTCnRpZ2FzZS5vcmcwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQC8pu2Xr8G5XntFh8CddypTornHRF6u7Y7RRvGH
Q6f/SuCdCvpqs4cAE7SFs4F8mtadddZvpSFg5TLEIPW1QZMVdlsFtSOdoih4q7Sx
7P1b+D9fpkX+2JJE48Vwy0+f22Z9FNewNrFeYiC2NJNZSpuiBkbkrQ1U75jeO2FF
bk0M1TsxFYcueyyM5O/KFEY73YzWavQ+F8ftj1q7wIMkOy0fgte/chsG64kSK5M5
AzbPln0x9p1g8Fd/uS1JwhM1H/X4APPyIpCR+VV5QbwoatF0fsb/zVBUXNPBAaF6
LUNQDsvjSb006VSAwMyFoaVd2ndvt80mG7hG1LkQRbRAZ/utAgMBAAGjggKmMIIC
ojAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFLwipUrXa356k3CcrRq2bSxQhUXpMB8G
A1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8GCCsGAQUFBwEBBGMwYTAu
BggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNyeXB0Lm9yZzAv
BggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8w
WwYDVR0RBFQwUoIOKi50aWdhc2UuY2xvdWSCDCoudGlnYXNlLm5ldIIMKi50aWdh
c2Uub3Jnggx0aWdhc2UuY2xvdWSCCnRpZ2FzZS5uZXSCCnRpZ2FzZS5vcmcwTAYD
VR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYa
aHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHz
APEAdgDnEvKwN34aYvuOyQxhhPHqezfLVh0RJlvz4PNL8kFUbgAAAXHY8iauAAAE
AwBHMEUCIQDHMgzqKnZ5K8DOZ6BJQgLgi8Rnj6aFhPB3lW8NDpI3nAIgLV8mkTbF
t1+2+8Vrhj8QRiFYOU3sMrO9GFyAKcMofosAdwAHt1wb5X1o//Gwxh0jFce65ld8
V5S3au68YToaadOiHAAAAXHY8ibeAAAEAwBIMEYCIQC/Riv7adDDXGuGzOsgQBAI
rn33KoU6mEK4BVCozM1f/QIhAPWsYc5jNhbcHn+nCK46j2et/ZwwjFMr8R8XnWyw
/0fIMA0GCSqGSIb3DQEBCwUAA4IBAQCUMYnzyQWtrkFAK9icKX3tRrhKeShiLuC7
VxAs4VvIxxX3pYO8NlDL/mwmT0L0LXP1qx4SQPh1EJ4Srgl5Szs9404lo1ukeu+V
cvYUijEeY5OtWBfsEVg91zP6Mr7jYDYG2LoGwhClz5MjHHfng51DntfiKc/1l4S4
xeU3+KKB59fiu13eeK4u4QxzwIJeexs7kDM7RwrwH79f7kfnY6Fk1fNcTjp0wjeD
p1Z0MUYBNw9nG6vB1pkyuyw8nShnUTn6gSqV7tU4Pw08Wy4uOf+nlSDBML4+neSo
KZBZa+QO+lpa665ScQj6/NHhTB5rqacuBXilM+McOYuu4MWLY4eh
-----END CERTIFICATE-----
subject=CN = tigase.org

issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

**Comment by woj-tek** [comment]
Thank you for reporting, should be ok now:
```
$ openssl s_client -connect xmpp.tigase.org:5269 -xmpphost tigase.org < /dev/null -starttls xmpp | openssl x509 -noout -dates
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = tigase.org
verify return:1
DONE
notBefore=Jul  2 05:26:06 2020 GMT
notAfter=Sep 30 05:26:06 2020 GMT
```
