### ISSUE TITLE
Migrating from MySQL to MongoDB

### ISSUE THREAD

**Issue by ku9nov** [tigase/tigase-server#50]
Dear, Team Tigase.
Soon we will need to change our production and ditch the RDS MySQL database in favor of MongoDB.
At the moment we are using user-db and auth-db on MySQL and we need to transfer all data from them to MongoDB.
Do you have any solutions or ideas about this?
Thank you, regards.

**Details:**
 - Tigase version: [7.0.2]
 - JVM flavour and version [OpenJDK8]
 - Operating system/distribution/version [Amazon Linux 2]
 - MongoDB [3.4]
 - MySQL [5.7]

**Comment by woj-tek** [comment]
First of all I'd like to suggest upgrading to the newest version of the Tigase - just the other day we released version [8.1.0](https://github.com/tigase/tigase-server/releases/tag/tigase-server-8.1.0).

Regarding issue at hand - there is no ready-made solution to migrate data between various databases. It would definitely be possible to create such tool. As an inspiration you could take a look at https://github.com/tigase/tigase-database-migrator (which converts data from ejabberd to Tigase, but it should be relatively strightforward to create custom converter that woulc convert from Tigase to Tigase) or [`Converter.java`](https://github.com/tigase/tigase-muc/blob/master/src/main/java/tigase/muc/repository/migration/Converter.java) class that upgrades MUC component, but the idea is the same - initialised component repository with the JDBC URL - in your case it would be two instances of the current version of the repository and then you would iterate over items from old repository (mysql) and insert in the new one (mongodb).

**Comment by woj-tek** [comment]
Of course you can contact us directly here: https://tigase.net/technical-support if you would like assistance of the Tigase Team.

**Comment by ku9nov** [comment]
Thank you for your quick response.
I understood you, and for now I will close this question.
Thank you. Regards.
