### ISSUE TITLE
How to config the custom field with PacketFilterIfc？

### ISSUE THREAD

**Issue by godpit** [tigase/tigase-server#6]
```
@Bean(name = "key-word-filter", parent = Kernel.class, active = true)
public class KeyWordFilter implements PacketFilterIfc {
       @ConfigField(desc = "", alias = "dzFilterUrl")
       private String dzFilterUrl = "";
}
```

the config.tdsl:
```
'key-word-filter' () {
    'dzFilterUrl' = 'https://xxxxxxx'
}

'sess-man' () {
    'incoming-filters' = 'tigase.xxxx.KeyWordFilter'
}
```

It did not work well. Thanks a lot!

**Comment by woj-tek** [comment]
Thank you for reporting this. Unfortunately currently it's not possible to configure custom packet filters.

We will fix the issue in the upcoming versions (#server-1097)

**Comment by godpit** [comment]
It  did not fix the issue with the latest  version (#server-1130).

**Comment by woj-tek** [comment]
Linked issue (#server-1130) is not related with this github issue. Packet filtering will be fixed in #server-1097

**Comment by woj-tek** [comment]
The issue was fixed and is already available in our nightly distribution packages and will be part of 8.2.0 release.
