### ISSUE TITLE
info about logging of "Using hardened-mode"

### ISSUE THREAD

**Issue by davidemarrone** [tigase/tigase-server#61]
**I have a problem with…**
In the log file: tigase.log.* I see a **lots** of entry of the type:
"SSLContextContainer.getHardenedMode(): Using hardened-mode: secure for domain: XYZ"
is it something that is possible to eliminate?

**Details:**
 - Tigase version: 8.1.1-b10861

**Comment by woj-tek** [comment]
By default you shouldn't see those entries as they are with level `INFO` and by default Tigase is using level `CONFIG`. At any rate, you can [adjust logging level](https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#_configuring_logging) for this particular class and change it to `CONFIG`:
```
logging () {
    loggers = {
        'tigase.io.SSLContextContainer' = {
            level = CONFIG
        }
    }
}
```

**Comment by davidemarrone** [comment]
Hi,
I have tried your conf, when I start the server in the log I see

```
logging {
    handlers {
        'java.util.logging.FileHandler' {
            count = '20'
            limit = '100000000'
            pattern = '/var/log/tigase/tigase.log'
        }
    }
    loggers {
        'tigase.io.SSLContextContainer' {
            level = 'CONFIG'
        }
    }
}

```
anyway is still logged the line

```
 [INFO    ] [             in_13-c2s ] SSLContextContainer.getHardenedMode(): Using hardened-mode: secure for domain: XYZ
```

from the doc:
```
loggers - Defines the level of logging for packages running in tigase server. This is similar to the --debug setting, however you must use tigase.{package} format. Default is NONE.
```

this means that I have to change the config level of all the package ```tigase.io``` and I cannot change the single level of the class ```tigase.io.SSLContextContainer``` ?

**Comment by woj-tek** [comment]
Have you configured any other packages via `debug` property (for example `io`)? If you want to increase `tigase.io` levels but keep `tigase.io.SSLContextContainer` at lower level then you should configure both of them via `logging`/`loggers` bean.

**Comment by davidemarrone** [comment]
no, the ```debug``` is not present in the config, so it should be to the default value

**Comment by woj-tek** [comment]
mea culpa, you should use level `WARNING` in the snippet above.

**Comment by davidemarrone** [comment]
ok thank you, now it works!
