### ISSUE TITLE
tigase@muc.tigase.org kicks my clients if I use them both

### ISSUE THREAD

**Issue by licaon-kter** [tigase/tigase-server#63]
Dino HEAD, Conversations 2.9.0+fcr, same account, same nick, different resources.

Log from Dino: https://gist.github.com/licaon-kter/5027b4fdb34144abc9e8deb537fabdf3 _(you can't see the error in the UI since it just reconnects)_
Conversations logcat outputs the same `110` and `170` codes _(you can see you are not joined since it does not reconnect)_

No issue if I use only one client.

**Comment by woj-tek** [comment]
```
[2020-11-17 17:03:19] <Wojtek>: @Licaon_Kter 110 - 'self presence', '170' - room is publicly logged; adding 170 in this case
[2020-11-17 17:04:25] <Wojtek>: it seems like a race condition (mostly something due to us using cluster and s2s connections having some delay when re-connecting)
```

**Comment by licaon-kter** [comment]
Any news?

**Comment by woj-tek** [comment]
Unfortunately not. We do keep this on our to-do.

Does it happen that often?

**Comment by licaon-kter** [comment]
100% of the time

I had to disable bookmark sync to have at least Conversations joined in that group.

**Comment by woj-tek** [comment]
@licaon-kter does it happen only with Dino?

**Comment by licaon-kter** [comment]
I didn't test other combos, just Dino+Conversations.

**Comment by woj-tek** [comment]
Could you try to reproduce it with other clients? Unfortunately I can't reproduce it nor run Dino (easily).

If you could also share packet id's from the most recent occurrence it would help

**Comment by licaon-kter** [comment]
I can repro with Converse.js and Profanity, same 110 and 170. Profanity closes the chat window.

**Comment by woj-tek** [comment]
@licaon-kter could you try now on muc.tigase.org?

**Comment by licaon-kter** [comment]
Thanks
