### ISSUE TITLE
Can't find sevice for STARTTLS command

### ISSUE THREAD

**Issue by davidemarrone** [tigase/tigase-server#64]
**I have a problem with…**
In the ```tigase-console.log``` I have different enties with

```
[WARNING ] [              in_1-c2s ] ClientConnectionManager.processCommand(): Can't find sevice for STARTTLS command: from=sess-man@my.domain.com, to=null, DATA=<iq id="tig1" type="set" from="sess-man@my.domain.com" to="c2s@my.domain.com/172.31.7.77_5222_1.2.3.4_55488"><command node="STARTTLS" xmlns="http://jabber.org/protocol/commands"><x type="submit" xmlns="jabber:x:data"/><proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/></command></iq>, SIZE=333, XMLNS=null, PRIORITY=NORMAL, PERMISSION=LOCAL, TYPE=set
```
why ```sess-man``` sends a STARTTLS ? I a problem with a client or an internal communication of a node of the cluster?

**Details (please complete the following information):**
 - Tigase version: 8.1.0-b5641

**Comment by woj-tek** [comment]
What's happening here: client establishes the connection (with ClientConnectionManager - c2s), at one point client tries to encrypt the connection so it sends `<starttls/>`. c2s informs about that fact SessionManager (`sess-man`) using above command. `sess-man` checks user session (and wheter TLS is available) and returns information whether it can proceed or not. Upon receiving the response the connection manager matches the session to send the information back to the client. However if it can't find the service the error is printed. This can happen if the client would disconnect during negotiating STARTTLS - sess-man would respond but in the meantime service would disappear from the c2s.

In general you could ignore this error.

**Comment by davidemarrone** [comment]
ok, thanks for the explanation
