### ISSUE TITLE
hoe to change max-queue-size?

### ISSUE THREAD

**Issue by doomspace** [tigase/tigase-server#69]
good evening!
how to change max-queue-size?

I start server, in 2-3 seconds i receive the next alert: 
```
 =============================================================================
jvm 1    |   You configured component of class tigase.server.xmppsession.SessionManager with packet queues total size set to 648
jvm 1    |   Component uses 96 queues which would give a limit of 12 packets per queue.
jvm 1    |   This value is too low for Tigase XMPP Server to run properly. Please adjust the configuration of the server.
jvm 1    |   max-queue-size should be set to at least 768
jvm 1    |   =============================================================================
jvm 1    |
jvm 1    | ShutdownThread started... 2020-12-18T12:59:02.064853500
jvm 1    |
jvm 1    | Total number of threads: 43
jvm 1    | No locked threads.
jvm 1    |
jvm 1    | Save thread-dump to file: logs/thread-dump.log, size: 21085
jvm 1    | ShutdownThread finished...
wrapper  | <-- Wrapper Stopped
```

i have found max-queue-size property inside the file tigase\etc\config-dump.properties and have changed it 5000 but it didn`t help.

**Details:**
 - Tigase version: [tigase-server-8.1.1-b10861-dist-max]
 - JVM flavour and version [OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.9.1_1]
 - Operating system/distribution/version [OS Name: Microsoft Windows Server 2019 Standard Evaluation, OS Version:  10.0.17763 N/A Build 17763]
 - CPU: virtual Intel Xeon E-2650,  2 GHz , 6 cores
 - RAM: 8.79 GB
 
Thanks

**Comment by woj-tek** [comment]
Have you set maximum HEAP size?

You can set queue size using [max-queue-size](https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#maxQueueSize), for example:
```
'max-queue-size' = 10000
```

**Comment by doomspace** [comment]
1) "maximum HEAP" - no, it`s fresh/clean installation
2) tigase\etc\config-dump.properties in the same file?

**Comment by doomspace** [comment]
also I have found additional warning: "init.properties does NOT EXISTS" - should I create file by my self???

===============================================
C:\inetpub\tigase>tigase
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 32-bit 3.5.26
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | componentInfo{Title=Tigase XML Tools, Version=4.1.0-b287/028d0a0a, Class=tigase.xml.XMLUtils}
jvm 1    | componentInfo{Title=Tigase Utils, Version=4.1.0-b437/a3e8f636, Class=tigase.util.ClassUtil}
jvm 1    | componentInfo{Title=Tigase XMPP Server, Version=8.1.0-b5641/99fb6fd4, Class=tigase.server.XMPPServer}
jvm 1    | componentInfo{Title=Tigase XMPP Server Distribution, Version=8.1.1-b10861/c891273a, Class=tigase.dist.XmppServerDist}
jvm 1    | [2020-12-21 21:15:27:206] [CONFIG  ] [  WrapperSimpleAppMain ] ConfiguratorAbstract.parseArgs() : Setting defaults: --property-file = etc/init.properties
jvm 1    | [2020-12-21 21:15:27:222] [FINEST  ] [  WrapperSimpleAppMain ] OldConfigHolder.detectPathAndFormat(): Provided property file C:\inetpub\tigase\etc\init.properties does NOT EXISTS! Trying to use default one etc/init.properties
jvm 1    | [2020-12-21 21:15:27:238] [CONFIG  ] [  WrapperSimpleAppMain ] ConfigHolder.loadFromDSLFiles()  : Loading configuration from file: etc\config.tdsl
jvm 1    | [2020-12-21 21:15:27:300] [CONFIG  ] [  WrapperSimpleAppMain ] ConfigHolder.loadConfiguration() : Loaded configuration:

**Comment by woj-tek** [comment]
> tigase\etc\config-dump.properties in the same file?

No, this one is an "effective" configuration. You should add this configuration to `etc/config.tdsl` file.

> also I have found additional warning: "init.properties does NOT EXISTS" - should I create file by my self???

No, this is the old configuration file that could be converted to the new format.

**Comment by doomspace** [comment]
thanks!
