### ISSUE TITLE
how can i Discovering Rooms

### ISSUE THREAD

**Issue by wqxcloud** [tigase/tigase-server#79]
**I have a problem with…**
A clear and concise description of what the problem is.

**Details (please complete the following information):**
 - Tigase version: [e.g. 8.1.0]
 - JVM flavour and version [e.g. AdoptOpenJDK11]
 - Operating system/distribution/version [e.g. Linux Ubuntu 20.04]
 The service discovery items ("disco#items") protocol enables an entity to query a service for a list of associated items, which in the case of a chat service would consist of the specific chat rooms hosted by the service.
How can i discovering rooms with the user`s jid,thanks
[https://xmpp.org/extensions/xep-0045.html#disco-service-features](https://xmpp.org/extensions/xep-0045.html#disco-service-features)

**Comment by woj-tek** [comment]
Just as it's stated in the example of the linked document:

Request:
```xml
<iq type='get' to='muc.tigase.org' id='muc-disco-info-1'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
```

Response:
```xml
<iq id='muc-disco-info-1' from='muc.tigase.org' xmlns='jabber:client' to='wojtek@tigase.org/2048393987-tigase-99' type='result'>
<query xmlns='http://jabber.org/protocol/disco#info'>
<identity name='Multi User Chat' category='conference' type='text'/>
<feature var='jabber:iq:version'/>
<feature var='http://jabber.org/protocol/disco#items'/>
<feature var='urn:xmpp:mam:1'/>
<feature var='vcard-temp'/>
<feature var='urn:xmpp:ping'/>
<feature var='http://jabber.org/protocol/commands'/>
<feature var='http://jabber.org/protocol/muc'/>
<feature var='http://tigase.org/protocol/muc#offline'/>
<feature var='http://jabber.org/protocol/disco#info'/>
<x xmlns='jabber:x:data' type='result'>
<field type='hidden' var='FORM_TYPE'>
<value>http://jabber.org/network/serverinfo</value>
</field>
<field var='abuse-addresses' type='text-multi'>
<value>mailto:support@tigase.net</value>
<value>xmpp:tigase@muc.tigase.org</value>
<value>https://tigase.net/technical-support</value>
</field>
</x>
</query>
</iq>
```


Please make sure that you have enabled MUC component and you are querying correct address. If that doesn't work please share more details.

**Comment by wqxcloud** [comment]
i  want to get the user`s joined rooms ,for example , i use mongodb database, but i don`t konw how to get room  jid of tig_muc_rooms table with  user`s jid of tig_muc_room_affiliations table 
`<iq from='chat.shakespeare.lit'
    id='zb8q41f4'
    to='hag66@shakespeare.lit/pda'
    type='result'>
  <query xmlns='http://jabber.org/protocol/disco#items'>
    <item jid='heath@chat.shakespeare.lit'
          name='A Lonely Heath'/>
    <item jid='coven@chat.shakespeare.lit'
          name='A Dark Cave'/>
    <item jid='forres@chat.shakespeare.lit'
          name='The Palace'/>
    <item jid='inverness@chat.shakespeare.lit'
          name='Macbeth&apos;s Castle'/>
  </query>
</iq>`
can you help me,thans

**Comment by woj-tek** [comment]
It's not possible to query it - it's the role of client application to keep track of joined MUC rooms.

We would recommend using MIX (https://tigase.net/tigase-im-mix/) as it's better suited for group-chat.

**Comment by wqxcloud** [comment]
> It's not possible to query it - it's the role of client application to keep track of joined MUC rooms.
> 
> We would recommend using MIX (https://tigase.net/tigase-im-mix/) as it's better suited for group-chat.

ok，thanks very much
