### ISSUE TITLE
When the message delivery rules are strict, the offline messages are not stored in the database

### ISSUE THREAD

**Issue by godpit** [tigase/tigase-server#8]
the config.tdsl:
```
'sess-man' () {
    amp {
        'delivery-rules' = 'strict'
    }
}
```

So i found the reason by debugging, such as:
<img width="1373" alt="WX20191125-155613@2x" src="https://user-images.githubusercontent.com/34534331/70373227-5262a380-1922-11ea-9c1d-516e52a2af95.png">

the class:  MessageAmp,  the method: postProcess, the line: 96, such as:

```java
if (packet.getElemName() == tigase.server.Message.ELEM_NAME && packet.getStanzaTo() != null && packet.getStanzaTo().getResource() != null) {
	return;
}
````

**Comment by woj-tek** [comment]
You configured `strict` delivery rules, therefore we are following [Message delivery rules](https://xmpp.org/rfcs/rfc6121.html#rules-localpart-fulljid-nomatch) to the dot:
> For a message stanza of type "normal", "groupchat", or "headline", the server MUST either (a) silently ignore the stanza or (b) return an error stanza to the sender, which SHOULD be <service-unavailable/>. 

You can try setting message type to `chat`

**Comment by godpit** [comment]
The type of message was chat. But the message was not stored in the database.

**Comment by godpit** [comment]
The from of message was xxx@yyy/pc, and the to of the message was bbb@yyy/phone,

**Comment by godpit** [comment]
The toJid of the message was a full JID, such as:
JID fromJid = JID.jidInstance("A", "xmpp.server");
JID toJid = JID.jidInstance("B", "xmpp.server", "phone");

So, when the client B was offline, i need the message was stored in the tig_offline_message with resource.

Because the message would not handle within some client, such as pc, some client (such as phone) would handle the message. 

However, when the phone client was not online, the message would be stored in the tig_offline_message.
The message would resent to the phone client until the phone client was online.

**Comment by woj-tek** [comment]
Thank you for the detailed description. We will investigate it further and let you know the outcome.

**Comment by woj-tek** [comment]
As the linked specification says:
> For a message stanza of type "chat": 
> * If there is no available or connected resource, the server MUST either (a) store the message offline for later delivery or (b) return an error stanza to the sender, which SHOULD be <service-unavailable/>. 

For the `strict` configuration we opted for the `(b)` option. If you want messages stored for offlien delivery you should use `inteligent` configuration of `'delivery-rules'`

**Comment by godpit** [comment]
For inteligent  configuration,  it was possible that the message would resent the pc client without handling the message, when the pc client was online. However, the pc client did not handle the message, so the message would be lost. But i just wanted the phone client handled the message.
So, how can i solve it? Thanks a lot!

**Comment by woj-tek** [comment]
Best way to handle it would be to use both/or any of the:
* [XEP-0280: Message Carbons](https://xmpp.org/extensions/xep-0280.html)
* [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html)
