### ISSUE TITLE
Could tigase support XEP-0272?

### ISSUE THREAD

**Issue by ChenMoGe2** [tigase/tigase-server#85]
**Is your feature request related to a problem? Please describe.**
Use video chat in chat room.

**Describe the solution you'd like**
I see the document of tigase and I don't find XEP-0272 (Muji)

**Describe alternatives you've considered**
Implement of XEP-0272

**Additional context**
Document of XEP-0272
https://xmpp.org/extensions/xep-0272.html

**Comment by woj-tek** [comment]
This is a client-side protocol and MUC is only used to forward the presence with Muji payload, which it should already do.

**Comment by ChenMoGe2** [comment]
> This is a client-side protocol and MUC is only used to forward the presence with Muji payload, which it should already do.

OK，Thanks
