### ISSUE TITLE
How can Tigase configurate OMEMO

### ISSUE THREAD

**Issue by ChenMoGe2** [tigase/tigase-server#89]
**I have a problem with…**
How can Tigase configurate OMEMO

**Details (please complete the following information):**
 - Tigase version: [e.g. 8.1.2]
 - JVM flavour and version [e.g. jdk11]
 - Operating system/distribution/version [e.g. Linux CentOS 7]

**Comment by woj-tek** [comment]
OMEMO is client-side protocol. It has some requirements on server (pubsub / pep options) but the defaults provided by Tigase XMPP Server already support OMEMO and no changes have to be made.

**Comment by ChenMoGe2** [comment]
@woj-tek OK,Thanks.It may be my setting error.
