### ISSUE TITLE
Why can't my upload module get up

### ISSUE THREAD

**Issue by alongkim** [tigase/tigase-server#9]
```
upload() {
    store {
        group-by-user = true
	path = '/data/upload/'
    }
}
```
this is my config.

**Comment by hantu85** [comment]
In the TDSL file format used for Tigase XMPP Server configuration files, you need to wrap `group-by-user ` in `'` chars as it contains `-` char in the property name. Your config should look like that:

````
upload() {
    store {
        'group-by-user' = true
        path = '/data/upload/'
    }
}
````

**Comment by alongkim** [comment]
> In the TDSL file format used for Tigase XMPP Server configuration files, you need to wrap `group-by-user ` in `'` chars as it contains `-` char in the property name. Your config should look like that:
> 
> ```
> upload() {
>     store {
>         'group-by-user' = true
>         path = '/data/upload/'
>     }
> }
> ```

thank you ,but it also can not work.i found it reqeust with my hostname ,not my domain name.

**Comment by alongkim** [comment]
> > In the TDSL file format used for Tigase XMPP Server configuration files, you need to wrap `group-by-user ` in `'` chars as it contains `-` char in the property name. Your config should look like that:
> > ```
> > upload() {
> >     store {
> >         'group-by-user' = true
> >         path = '/data/upload/'
> >     }
> > }
> > ```
> 
> thank you ,but it also can not work.i found it reqeust with my hostname ,not my domain name.

just like ` http://tigase-b:8080/upload/dragon@youliaoxmpp.com/28f7f619-80a9-46fa-86a1-8e8986959d3d/2bfb3ff8490549d8abccac906e0740e8.jpg` the 'tigase-b' is my hostname,my domain is 'youliaoxmpp'.

**Comment by woj-tek** [comment]
You can configure that using [http-upload options](https://docs.tigase.net/tigase-http-api/2.0.0/Tigase_HTTP-API_Guide/html/#_uri_template_format) and using `serverName` option:
```
upload() {
    store {
        'group-by-user' = true
        path = '/data/upload/'
        serverName = 'youliaoxmpp'
    }
}
```

**Comment by alongkim** [comment]
> serverName = 'youliaoxmpp'

thank you very much. it is ok.
